language: c

compiler: gcc

os:
  - linux
  - osx

branches:
  - master
  - /^pcb-.*-RELEASE/
  - /^LP.*/
  - /home\/cparker\/.*  

addons:
  apt:
    packages: gettext autopoint intltool

before_script:
  - ./autogen.sh

script:
  - ./configure --disable-doc
