language: c

compiler: gcc

os:
  - linux
  - osx

branches:
  - master
  - travis-ci
  - /^pcb-.*-RELEASE/
  - /^LP.*/
  - /home\/cparker\/.*  

addons:
  apt:
    packages: 
      - gettext 
      - autopoint 
      - intltool 
      - libgtk2.0-dev 
      - libgtkglext1-dev 
      - libgd-dev
      - gerbv

before_script:
  - ./autogen.sh

script:
  - ./configure --disable-doc --disable-dbus --disable-update-desktop-database 
    && make && make check && make distcheck

after_failure:
  - [ -f src/unittest.log ] && cat src/unittest.log
  - [ -f tests/test-suite.log ] && cat tests/test-suite.log
